//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBigPackApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Patrinymic { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int PassportSerias { get; set; }
        public int PassportNumber { get; set; }
        public string IssuedBy { get; set; }
        public string Adress { get; set; }
        public int BankDetails { get; set; }
    }
}
